version: '3'

services:
  devbook_db:
    container_name: devbook_db
    image: mysql:8.0.34
    restart: always
    ports:
      - '3311:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --bind-address=0.0.0.0

volumes:
  mysql-data:
